spring.application.name=workflow_orchestration
spring.datasource.url=jdbc:mysql://localhost:3306/workflow

spring.datasource.username=root

spring.datasource.password=Xux@72240

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true